---
- name: Nginx Server Installation
  hosts: training
 # become: yes
  tasks:
  - name: Install latest nginx
    yum:
      name: nginx
      state: latest
  - name: Enable nginx service
    service:
      name: nginx
      enabled: true
      state: started
